export const CUSTOM_SUBCLASS_NAME_MAX_LENGTH = 100;
export const CUSTOM_SUBCLASS_DESCRIPTION_MAX_LENGTH = 10000;
export const CUSTOM_SUBCLASS_FEATURE_NAME_MAX_LENGTH = 100;
export const CUSTOM_SUBCLASS_FEATURE_DESCRIPTION_MAX_LENGTH = 10000;
